import { Inter } from "next/font/google";
import "./globals.css";
import { getServerSession } from "next-auth";
import SessionProvider from "../utils/SessionProvider";
import Navbar from "components/Navbar";
// import Nav from "components/Nav";
import "../css/style.css"; // Thêm .css để import file CSS
import "../css/colors/scheme-01.css";
import "../css/bootstrap.min.css";
import "../css/mdb.min.css";
// import "../css/plugins.css"
import "../css/coloring.css";

import { ToastContainer, toast } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';


const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const session = await getServerSession();
  return (
    <html lang="en">
      <body className={inter.className}>
        <SessionProvider session={session}>
          <Navbar session={session}/>
          <ToastContainer/>
          {children }
        </SessionProvider>
      </body>
    </html>
  );
}
